In [1]:
import tensorflow as tf
import numpy as np

/home/kenn/anaconda3/envs/tf_base/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters


In [2]:
with tf.Session() as sess:
    W = tf.Variable([[1,2,3],
                 [3,4,5]],dtype = tf.float32, name="weights")
    b = tf.Variable([[1,2,3]],dtype = tf.float32, name="biases")
    init = tf.global_variables_initializer()
    saver = tf.train.Saver()
    sess.run(init)
    print(sess.run(W))
    print(sess.run(b))
    save_path = saver.save(sess,"logs/my_net/save_net.ckpt")
    print("Save to path:", save_path)

[[1. 2. 3.]
 [3. 4. 5.]]
[[1. 2. 3.]]
Save to path: logs/my_net/save_net.ckpt


In [ ]:
# 读取的时候需要定义一样的shape和dtype

In [3]:
with tf.Session() as sess:
    W = tf.Variable(tf.zeros([2,3]),dtype = tf.float32, name="weights")
    b = tf.Variable(tf.zeros([1,3]),dtype = tf.float32, name="biases")
    init = tf.global_variables_initializer()
    sess.run(init)
    print(sess.run(W))
    print(sess.run(b))

[[0. 0. 0.]
 [0. 0. 0.]]
[[0. 0. 0.]]


In [6]:
tf.reset_default_graph()
with tf.Session() as sess:
    W = tf.Variable(tf.zeros([2,3]),dtype = tf.float32, name="weights")
    b = tf.Variable(tf.zeros([1,3]),dtype = tf.float32, name="biases")
    saver = tf.train.Saver()
    saver.restore(sess, "logs/Save and load/save_net.ckpt")
    print("weights:", sess.run(W))
    print("weights:", sess.run(b))
    
    

INFO:tensorflow:Restoring parameters from logs/my_net/save_net.ckpt
weights: [[1. 2. 3.]
 [3. 4. 5.]]
weights: [[1. 2. 3.]]
